# Generated by Django 5.0 on 2023-12-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
