# Generated by Django 5.0 on 2023-12-24 05:38

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dripper',
            fields=[
                ('id', models.CharField(default=base.models.generate_ulid, max_length=128, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'dripper',
            },
        ),
        migrations.CreateModel(
            name='EspressoMachine',
            fields=[
                ('id', models.CharField(default=base.models.generate_ulid, max_length=128, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'espresso_machine',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.CharField(default=base.models.generate_ulid, max_length=128, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'scale',
            },
        ),
    ]
