# Generated by Django 5.0 on 2023-12-25 09:09

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grinde',
            fields=[
                ('id', models.CharField(default=base.models.generate_ulid, max_length=128, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'grinder',
            },
        ),
    ]
