# Generated by Django 5.0 on 2023-12-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_grinde'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grinde',
            new_name='Grinder',
        ),
    ]
