# Generated by Django 5.0 on 2023-12-20 14:47

import django.db.models.deletion
import grinder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrinderBrand',
            fields=[
                ('id', models.CharField(default=grinder.models.generate_ulid, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Grinder',
            fields=[
                ('id', models.CharField(default=grinder.models.generate_ulid, max_length=128, primary_key=True, serialize=False)),
                ('model', models.CharField(default='', max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grinder_brand', to='grinder.grinderbrand')),
            ],
        ),
    ]
